config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'message', to: 'messages#create'
  resources :users, except: [:new]

  # Defines the root path route ("/")
  # root "articles#index"
  mount ActionCable.server, at:'/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
    validates :body, presence: true,length:{minimum: 5,maximum: 250}
    validates :user, presence: true
    belongs_to :user

    scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, uniqueness: true,presence: true,length:{minimum: 5,maximum: 15}
    has_secure_password
    has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||=User.find(session[:user_id]) if session[:user_id]
    end
    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:error] ="You need to login"
            redirect_to login_path
        end
    end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    before_action :require_user
    def index
        @message=Message.new
        @messages=Message.custom_display
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  def create
    message=current_user.messages.build(message_params)
    p message
    if message.save
      ActionCable.server.broadcast("chatroom_channel" ,{rendered_message:render_message(message)})
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def render_message(message)
    render(partial:'message',locals:{message: message})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :logged_in_redirect,only:[:new,:create]
    def new
    end

    def create
        entered_params=get_user_params
        user=User.find_by(username:entered_params[:username])
        if user && user.authenticate(entered_params[:password])
            session[:user_id]=user.id
            flash.now[:success]="logged in"
            redirect_to root_path
        else
            flash.now[:error]="Incorrect password"
            render 'new'
        end
    end

    def destroy
        session[:user_id]=nil
        flash[:success]="Logged Out"
        redirect_to login_path
    end

    def signup
    end
    
    private
    def get_user_params
        params.require("session").permit(:password,:username)
    end

    def logged_in_redirect
        if logged_in?
            flash[:error]="Already logged in"
            redirect_to root_path
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user=User.new
    end

    def create
        @user=User.new(get_user_params)
        if @user.save
            session[:user_id]=@user.id
            flash.now[:success]="Signed up!"
            redirect_to root_path
        else
            flash.now[:error] = 'User was not created!' # or :alert
            render "new"
        end
    end
    
    private
    def get_user_params
      params.require(:user).permit(:username, :password,:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular purple comments outline icon"></i>
  Chatroom
</h2>
<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      
<div class="content" id="messages">
  <div class="ui feed" id="messages-container">

          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message,html:{class:"ui reply form",role:"form"},url:message_path, remote: true) do |f| %>

          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body %>
              <%= f.button ' <i class="bordered inverted orange edit icon"></i>'.html_safe%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item active">
            Friends
          </a>
        </div>
      </div>
    </div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type,message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_type %>
    </div>
    <%= message_content %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui large inverted menu">
  <div class="ui container">
    <%= link_to "Chatroom", root_path, class: "item"  %>

    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
  <%= link_to "Logout", logout_path,data:{ turbo_method: :delete}, class: "item"  %>
<% else %>
  <%= link_to "Login", login_path, class: "item"  %>
<% end %>

        </div>
      </div>
<% if !logged_in? %>

      <div class="item">
  <%= link_to "Login", login_path, class: "ui primary button"  %>

      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <%= javascript_include_tag "turbo", type: "module" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= favicon_link_tag %>
    <%= javascript_importmap_tags %>

  </head>

  <body>


<div class="ui container">


    <%= render 'layouts/navigation' %>


      <%= render 'layouts/messages' %>

      <%= yield %>

</div>

  </body>
</html>

app/views/messages/_message.html.erb
 
<div class="content">
  <div class="summary">
    <em><%= message.user.username %></em>: <%= message.body %>
  </div>
</div>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/users/new.html.erb
<h2 class="ui center aligned icon header">
  <i class="space shuttle purple"></i>
  Signup
</h2>
<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <%= form_for(:user, html:{class:"ui form",role:"form"},url: users_path) do |f|%>
        <div class="field">
          <%= f.label :username, "Username" %>
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: "Username"  %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <%= f.label :password, "Password" %>
          <div class="ui left icon input">
            <%= f.password_field :password, placeholder: "Password"  %>
            <i class="lock icon"></i>
          </div>
        </div>
        <%= f.button "Signup",class:"ui blue submit button"  %>
      </div>
      <div class="middle aligned column">
        <div class="ui big orange button">
          <i class="signup icon"></i>
          <%= link_to "Login Instead",login_path, class: "white"  %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>